import https from 'https';
import { getSpApiClient, getSpApiClientByRegion } from './client';
import {
  detectMarketplaceCode,
  generateTransactionId,
  computeDateOnly,
} from './transactionParser';
import logger from '../../config/logger';
import type { MarketplaceConfig } from '../../types';
import type { FinancialTransaction } from '../../types';

/**
 * Fetch financial events via SP-API Finances API (listFinancialEvents).
 * Returns all marketplaces for the credential in one call.
 * Handles pagination via NextToken.
 */
export async function fetchTransactionsByDateRange(
  marketplace: MarketplaceConfig,
  startDate: Date,
  _endDate: Date
): Promise<FinancialTransaction[]> {
  const client = marketplace.credential_id
    ? await getSpApiClient(marketplace.credential_id)
    : await getSpApiClientByRegion(marketplace.region.toLowerCase());

  logger.info(`[SP-API] Fetching financial events for credential ${marketplace.credential_id} (${marketplace.country_code}): from ${startDate.toISOString()}`);

  const allTransactions: FinancialTransaction[] = [];
  let nextToken: string | undefined;
  let pageCount = 0;

  do {
    const query: Record<string, string> = {
      PostedAfter: startDate.toISOString(),
      MaxResultsPerPage: '100',
    };
    if (nextToken) query.NextToken = nextToken;

    const response: any = await client.callAPI({
      operation: 'listFinancialEvents',
      endpoint: 'finances',
      query,
    });

    const events = response?.FinancialEvents || response;
    const transactions = flattenFinancialEvents(events, marketplace.credential_id);
    allTransactions.push(...transactions);

    nextToken = response?.NextToken;
    pageCount++;

    if (pageCount % 10 === 0) {
      logger.info(`[SP-API] Financial events page ${pageCount}: ${allTransactions.length} transactions so far`);
    }

    // Rate limit: 0.5 RPS for listFinancialEvents
    if (nextToken) await new Promise(resolve => setTimeout(resolve, 500));
  } while (nextToken);

  logger.info(`[SP-API] Fetched ${allTransactions.length} financial transactions in ${pageCount} pages`);
  return allTransactions;
}

/**
 * Fetch settlement report data for categories NOT covered by Finances API:
 * FBA Inventory Fee, Shipping Services, FBA Transaction Fee, etc.
 * Settlement reports are auto-generated by Amazon every ~2 weeks.
 */
export async function fetchSettlementTransactions(
  marketplace: MarketplaceConfig,
  startDate: Date,
): Promise<FinancialTransaction[]> {
  const client = marketplace.credential_id
    ? await getSpApiClient(marketplace.credential_id)
    : await getSpApiClientByRegion(marketplace.region.toLowerCase());

  logger.info(`[SP-API] Fetching settlement reports for credential ${marketplace.credential_id} since ${startDate.toISOString()}`);

  // List settlement reports created after startDate
  const response: any = await client.callAPI({
    operation: 'getReports',
    endpoint: 'reports',
    query: {
      reportTypes: 'GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2',
      createdSince: startDate.toISOString(),
      pageSize: '20',
    },
  });

  const reports = response.reports || response || [];
  const doneReports = reports.filter((r: any) => r.processingStatus === 'DONE' && r.reportDocumentId);
  logger.info(`[SP-API] Found ${doneReports.length} completed settlement reports`);

  const allTransactions: FinancialTransaction[] = [];
  const processedSettlements = new Set<string>();

  for (const report of doneReports) {
    const settlementId = report.reportId;
    if (processedSettlements.has(settlementId)) continue;
    processedSettlements.add(settlementId);

    try {
      const doc: any = await client.callAPI({
        operation: 'getReportDocument',
        endpoint: 'reports',
        path: { reportDocumentId: report.reportDocumentId },
      });

      const tsv = await downloadDocument(doc.url);
      const transactions = parseSettlementTsv(tsv, marketplace.credential_id, startDate, marketplace.country_code.toLowerCase());
      allTransactions.push(...transactions);

      logger.info(`[SP-API] Settlement ${settlementId}: ${transactions.length} supplementary transactions`);
    } catch (err: any) {
      logger.error(`[SP-API] Failed to process settlement ${settlementId}:`, err.message);
    }

    // Rate limit
    await new Promise(resolve => setTimeout(resolve, 2000));
  }

  logger.info(`[SP-API] Total ${allTransactions.length} settlement supplementary transactions`);
  return allTransactions;
}

function downloadDocument(url: string): Promise<string> {
  return new Promise((resolve, reject) => {
    https.get(url, (res) => {
      let body = '';
      res.on('data', (chunk: string) => body += chunk);
      res.on('end', () => resolve(body));
      res.on('error', reject);
    }).on('error', reject);
  });
}

/**
 * Parse settlement TSV and extract only rows NOT covered by Finances API.
 * Covers: other-transaction (FBA fees, shipping services, storage, etc.)
 * Skips: Order, Refund, ServiceFee, etc. (already from Finances API)
 */
function parseSettlementTsv(tsv: string, credentialId: number | null, startDate: Date, defaultMarketplaceCode: string): FinancialTransaction[] {
  const lines = tsv.split('\n').filter(l => l.trim());
  if (lines.length < 2) return [];

  const headers = lines[0].split('\t');
  const col = (name: string) => headers.indexOf(name);

  const typeIdx = col('transaction-type');
  const amtTypeIdx = col('amount-type');
  const amtDescIdx = col('amount-description');
  const amountIdx = col('amount');
  const orderIdIdx = col('order-id');
  const skuIdx = col('sku');
  const postedDateIdx = col('posted-date-time') >= 0 ? col('posted-date-time') : col('posted-date');
  const marketplaceIdx = col('marketplace-name');
  const fulfillmentIdx = col('fulfillment-id');

  if (typeIdx < 0 || amountIdx < 0) return [];

  // Only process types NOT covered by Finances API
  const financesApiTypes = new Set(['Order', 'Refund', 'ServiceFee', 'Grade and Resell Fees', 'SAFE-T Reimbursement', 'Order_Retrocharge']);

  // Reserve entries are Disbursement-equivalent (not profitability-relevant)
  const skipDescriptions = ['previous reserve amount balance', 'current reserve amount'];

  // Group by order-id + posted-date to aggregate amount rows into single transactions
  const txnMap = new Map<string, {
    postedDate: Date; orderId: string; sku: string; marketplace: string;
    fulfillment: string; amtType: string; amtDesc: string; txnType: string;
    amounts: { type: string; desc: string; amount: number }[];
  }>();

  for (let i = 1; i < lines.length; i++) {
    const c = lines[i].split('\t');
    const txnType = c[typeIdx] || '';

    // Skip types already handled by Finances API
    if (financesApiTypes.has(txnType) || !txnType) continue;

    const postedStr = c[postedDateIdx] || '';
    const postedDate = postedStr ? new Date(postedStr) : null;
    if (!postedDate || isNaN(postedDate.getTime())) continue;
    if (postedDate < startDate) continue;

    const orderId = c[orderIdIdx] || '';
    const amount = parseFloat(c[amountIdx] || '0');
    const amtType = c[amtTypeIdx] || '';
    const amtDesc = c[amtDescIdx] || '';

    // Skip Reserve entries (Disbursement-equivalent, not for profitability)
    if (skipDescriptions.some(s => amtDesc.toLowerCase().includes(s))) continue;

    // Group key: txnType + orderId + postedDate (to aggregate multi-row entries)
    const key = `${txnType}|${orderId}|${postedStr}|${c[skuIdx] || ''}`;

    if (!txnMap.has(key)) {
      txnMap.set(key, {
        postedDate,
        orderId,
        sku: c[skuIdx] || '',
        marketplace: c[marketplaceIdx] || '',
        fulfillment: c[fulfillmentIdx] || '',
        amtType,
        amtDesc,
        txnType,
        amounts: [],
      });
    }
    txnMap.get(key)!.amounts.push({ type: amtType, desc: amtDesc, amount });
  }

  const transactions: FinancialTransaction[] = [];

  for (const [, entry] of txnMap) {
    const total = entry.amounts.reduce((s, a) => s + a.amount, 0);
    const categoryType = categorizeSettlementType(entry.txnType, entry.amtType, entry.amtDesc);
    const marketplaceCode = detectMarketplaceCode(entry.marketplace) || defaultMarketplaceCode;
    const dateOnly = computeDateOnly(entry.postedDate, marketplaceCode);
    const description = entry.amounts.map(a => a.desc).filter(Boolean).join('; ') || entry.txnType;

    const transactionId = generateTransactionId(
      marketplaceCode, entry.postedDate, categoryType,
      entry.orderId, entry.sku, total
    );

    transactions.push({
      transaction_id: transactionId,
      file_name: 'sp-api-settlement',
      transaction_date: entry.postedDate,
      date_only: dateOnly,
      type: entry.amtDesc || entry.txnType,
      category_type: categoryType,
      order_id: entry.orderId,
      sku: entry.sku,
      description,
      marketplace: entry.marketplace,
      marketplace_code: marketplaceCode,
      fulfillment: entry.fulfillment || 'Unknown',
      order_postal: '',
      quantity: 0,
      product_sales: 0,
      promotional_rebates: 0,
      selling_fees: 0,
      fba_fees: 0,
      other_transaction_fees: 0,
      other: total,
      vat: 0,
      liquidations: 0,
      total,
      credential_id: credentialId,
    });
  }

  return transactions;
}

function categorizeSettlementType(txnType: string, amtType: string, amtDesc: string): string {
  const desc = amtDesc.toLowerCase();
  const type = amtType.toLowerCase();

  if (desc.includes('storage fee') || desc.includes('inventory fee') ||
      type.includes('fba inventory')) return 'FBA Inventory Fee';
  if (desc.includes('shipping label') || desc.includes('shipping services')) return 'Shipping Services';
  if (desc.includes('removal') || desc.includes('disposal')) return 'Delivery Services';
  if (desc.includes('subscription')) return 'Service Fee';
  if (desc.includes('fba inbound') || desc.includes('placement service')) return 'FBA Inventory Fee';
  if (desc.includes('fba transaction')) return 'FBA Transaction Fee';
  if (type.includes('reimbursement')) return 'Adjustment';
  if (desc.includes('reserve')) return 'Others';
  if (desc.includes('adjustment')) return 'Adjustment';

  return 'Others';
}

// --- Flatten structured events into flat AmzSellMetrics rows ---

function flattenFinancialEvents(events: any, credentialId: number | null): FinancialTransaction[] {
  const transactions: FinancialTransaction[] = [];
  if (!events) return transactions;

  if (Array.isArray(events.ShipmentEventList)) {
    for (const e of events.ShipmentEventList) transactions.push(...flattenShipmentEvent(e, 'Order', credentialId));
  }
  if (Array.isArray(events.RefundEventList)) {
    for (const e of events.RefundEventList) transactions.push(...flattenShipmentEvent(e, 'Refund', credentialId));
  }
  if (Array.isArray(events.AdjustmentEventList)) {
    for (const e of events.AdjustmentEventList) transactions.push(...flattenAdjustmentEvent(e, credentialId));
  }
  if (Array.isArray(events.ServiceFeeEventList)) {
    for (const e of events.ServiceFeeEventList) transactions.push(...flattenServiceFeeEvent(e, credentialId));
  }
  if (Array.isArray(events.SAFETReimbursementEventList)) {
    for (const e of events.SAFETReimbursementEventList) transactions.push(...flattenSafetEvent(e, credentialId));
  }
  if (Array.isArray(events.FBALiquidationEventList)) {
    for (const e of events.FBALiquidationEventList) transactions.push(...flattenLiquidationEvent(e, credentialId));
  }
  if (Array.isArray(events.CouponPaymentEventList)) {
    for (const e of events.CouponPaymentEventList) transactions.push(...flattenCouponEvent(e, credentialId));
  }
  if (Array.isArray(events.ChargeRefundEventList)) {
    for (const e of events.ChargeRefundEventList) transactions.push(...flattenShipmentEvent(e, 'Chargeback Refund', credentialId));
  }
  // ChargebackEventList and GuaranteeClaimEventList share Refund structure (ShipmentItemAdjustmentList)
  if (Array.isArray(events.ChargebackEventList)) {
    for (const e of events.ChargebackEventList) transactions.push(...flattenShipmentEvent(e, 'Chargeback', credentialId));
  }
  if (Array.isArray(events.GuaranteeClaimEventList)) {
    for (const e of events.GuaranteeClaimEventList) transactions.push(...flattenShipmentEvent(e, 'Guarantee Claim', credentialId));
  }
  if (Array.isArray(events.ProductAdsPaymentEventList)) {
    for (const e of events.ProductAdsPaymentEventList) transactions.push(flattenProductAdsEvent(e, credentialId));
  }
  if (Array.isArray(events.RetrochargeEventList)) {
    for (const e of events.RetrochargeEventList) transactions.push(flattenRetrochargeEvent(e, credentialId));
  }
  if (Array.isArray(events.DebtRecoveryEventList)) {
    for (const e of events.DebtRecoveryEventList) transactions.push(flattenDebtRecoveryEvent(e, credentialId));
  }
  if (Array.isArray(events.RemovalShipmentEventList)) {
    for (const e of events.RemovalShipmentEventList) transactions.push(...flattenRemovalShipmentEvent(e, credentialId));
  }
  if (Array.isArray(events.RemovalShipmentAdjustmentEventList)) {
    for (const e of events.RemovalShipmentAdjustmentEventList) transactions.push(...flattenRemovalShipmentAdjustmentEvent(e, credentialId));
  }

  return transactions;
}

// --- Amount helpers ---

function getChargeAmount(list: any[], type: string): number {
  if (!Array.isArray(list)) return 0;
  return list.find((c: any) => c.ChargeType === type)?.ChargeAmount?.CurrencyAmount || 0;
}

function getFeeAmount(list: any[], type: string): number {
  if (!Array.isArray(list)) return 0;
  return list.find((f: any) => f.FeeType === type)?.FeeAmount?.CurrencyAmount || 0;
}

function sumFees(list: any[], exclude: string[] = []): number {
  if (!Array.isArray(list)) return 0;
  return list.filter((f: any) => !exclude.includes(f.FeeType))
    .reduce((s: number, f: any) => s + (f.FeeAmount?.CurrencyAmount || 0), 0);
}

function sumCharges(list: any[]): number {
  if (!Array.isArray(list)) return 0;
  return list.reduce((s: number, c: any) => s + (c.ChargeAmount?.CurrencyAmount || 0), 0);
}

function sumPromotions(list: any[]): number {
  if (!Array.isArray(list)) return 0;
  return list.reduce((s: number, p: any) => s + (p.PromotionAmount?.CurrencyAmount || 0), 0);
}

function sumTaxWithheld(list: any[]): number {
  if (!Array.isArray(list)) return 0;
  let total = 0;
  for (const tw of list) {
    if (Array.isArray(tw.TaxesWithheld)) {
      for (const t of tw.TaxesWithheld) total += t.ChargeAmount?.CurrencyAmount || 0;
    }
  }
  return total;
}

// --- Event type flatteners ---

function flattenShipmentEvent(event: any, categoryType: string, credentialId: number | null): FinancialTransaction[] {
  const transactions: FinancialTransaction[] = [];
  const postedDate = event.PostedDate ? new Date(event.PostedDate) : null;
  if (!postedDate || isNaN(postedDate.getTime())) return transactions;

  const orderId = event.AmazonOrderId || '';
  const marketplaceValue = event.MarketplaceName || '';
  const marketplaceCode = detectMarketplaceCode(marketplaceValue);

  // Orders use ShipmentItemList; Refunds use ShipmentItemAdjustmentList
  const itemList = event.ShipmentItemList?.length > 0
    ? event.ShipmentItemList
    : event.ShipmentItemAdjustmentList || [];

  for (const item of itemList) {
    const sku = item.SellerSKU || '';
    const quantity = item.QuantityShipped || 0;

    // Orders use ItemChargeList/ItemFeeList; Refunds use *AdjustmentList variants
    const charges = item.ItemChargeList || item.ItemChargeAdjustmentList || [];
    const fees = item.ItemFeeList || item.ItemFeeAdjustmentList || [];
    const promos = item.PromotionList || item.PromotionAdjustmentList || [];

    const productSales = getChargeAmount(charges, 'Principal');
    const tax = getChargeAmount(charges, 'Tax');
    const shippingCharge = getChargeAmount(charges, 'ShippingCharge');
    const shippingTax = getChargeAmount(charges, 'ShippingTax');

    const commission = getFeeAmount(fees, 'Commission');
    const fbaPerUnit = getFeeAmount(fees, 'FBAPerUnitFulfillmentFee');
    const fbaPerOrder = getFeeAmount(fees, 'FBAPerOrderFulfillmentFee');
    const fbaWeightBased = getFeeAmount(fees, 'FBAWeightBasedFee');
    const fbaFees = fbaPerUnit + fbaPerOrder + fbaWeightBased;
    const sellingFees = commission;
    const otherFees = sumFees(fees, [
      'Commission', 'FBAPerUnitFulfillmentFee', 'FBAPerOrderFulfillmentFee', 'FBAWeightBasedFee',
    ]);

    const promotionalRebates = sumPromotions(promos);
    const vat = sumTaxWithheld(item.ItemTaxWithheldList);
    const fulfillment = fbaFees !== 0 ? 'FBA' : 'FBM';

    const total = productSales + tax + shippingCharge + shippingTax +
      sellingFees + fbaFees + otherFees + promotionalRebates;

    const transactionId = generateTransactionId(marketplaceCode, postedDate, categoryType, orderId, sku, total);
    const dateOnly = computeDateOnly(postedDate, marketplaceCode);

    transactions.push({
      transaction_id: transactionId,
      file_name: 'sp-api-sync',
      transaction_date: postedDate,
      date_only: dateOnly,
      type: categoryType,
      category_type: categoryType,
      order_id: orderId,
      sku,
      description: '',
      marketplace: marketplaceValue,
      marketplace_code: marketplaceCode,
      fulfillment,
      order_postal: '',
      quantity,
      product_sales: productSales,
      promotional_rebates: promotionalRebates,
      selling_fees: sellingFees,
      fba_fees: fbaFees,
      other_transaction_fees: otherFees,
      other: shippingCharge + shippingTax,
      vat,
      liquidations: 0,
      total,
      credential_id: credentialId,
    });
  }

  return transactions;
}

function flattenAdjustmentEvent(event: any, credentialId: number | null): FinancialTransaction[] {
  const transactions: FinancialTransaction[] = [];
  const postedDate = event.PostedDate ? new Date(event.PostedDate) : null;
  if (!postedDate || isNaN(postedDate.getTime())) return transactions;

  const adjustmentType = event.AdjustmentType || 'Adjustment';

  for (const item of (event.AdjustmentItemList || [])) {
    const total = item.TotalAmount?.CurrencyAmount || 0;
    const sku = item.SellerSKU || item.ASIN || '';
    const orderId = item.OrderId || '';

    const transactionId = generateTransactionId('', postedDate, adjustmentType, orderId, sku, total);
    const dateOnly = computeDateOnly(postedDate, '');

    transactions.push({
      transaction_id: transactionId, file_name: 'sp-api-sync',
      transaction_date: postedDate, date_only: dateOnly,
      type: adjustmentType, category_type: 'Adjustment',
      order_id: orderId, sku, description: adjustmentType,
      marketplace: '', marketplace_code: '', fulfillment: 'Unknown', order_postal: '',
      quantity: item.Quantity || 0,
      product_sales: 0, promotional_rebates: 0, selling_fees: 0,
      fba_fees: 0, other_transaction_fees: 0, other: total,
      vat: 0, liquidations: 0, total,
      credential_id: credentialId,
    });
  }

  return transactions;
}

function flattenServiceFeeEvent(event: any, credentialId: number | null): FinancialTransaction[] {
  const totalFee = (event.FeeList || []).reduce((s: number, f: any) => s + (f.FeeAmount?.CurrencyAmount || 0), 0);
  const feeReason = event.FeeReason || 'Service Fee';
  const postedDate = event.PostedDate ? new Date(event.PostedDate) : new Date();

  const transactionId = generateTransactionId('', postedDate, feeReason, event.AmazonOrderId || '', event.SellerSKU || '', totalFee);
  const dateOnly = computeDateOnly(postedDate, '');

  return [{
    transaction_id: transactionId, file_name: 'sp-api-sync',
    transaction_date: postedDate, date_only: dateOnly,
    type: feeReason, category_type: 'Service Fee',
    order_id: event.AmazonOrderId || '', sku: event.SellerSKU || '',
    description: event.FeeDescription || feeReason,
    marketplace: '', marketplace_code: '', fulfillment: 'Unknown', order_postal: '',
    quantity: 0,
    product_sales: 0, promotional_rebates: 0, selling_fees: 0,
    fba_fees: 0, other_transaction_fees: totalFee, other: 0,
    vat: 0, liquidations: 0, total: totalFee,
    credential_id: credentialId,
  }];
}

function flattenSafetEvent(event: any, credentialId: number | null): FinancialTransaction[] {
  const transactions: FinancialTransaction[] = [];
  const postedDate = event.PostedDate ? new Date(event.PostedDate) : null;
  if (!postedDate || isNaN(postedDate.getTime())) return transactions;

  const reasonCode = event.ReasonCode || 'SAFE-T';

  for (const item of (event.SAFETReimbursementItemList || [])) {
    const total = sumCharges(item.ItemChargeList || []);
    const transactionId = generateTransactionId('', postedDate, 'SAFE-T Reimbursement', event.SAFETClaimId || '', item.SellerSKU || '', total);
    const dateOnly = computeDateOnly(postedDate, '');

    transactions.push({
      transaction_id: transactionId, file_name: 'sp-api-sync',
      transaction_date: postedDate, date_only: dateOnly,
      type: `SAFE-T Reimbursement - ${reasonCode}`, category_type: 'SAFE-T Reimbursement',
      order_id: event.SAFETClaimId || '', sku: item.SellerSKU || '', description: reasonCode,
      marketplace: '', marketplace_code: '', fulfillment: 'FBA', order_postal: '',
      quantity: item.Quantity || 0,
      product_sales: 0, promotional_rebates: 0, selling_fees: 0,
      fba_fees: 0, other_transaction_fees: 0, other: total,
      vat: 0, liquidations: 0, total,
      credential_id: credentialId,
    });
  }

  return transactions;
}

function flattenLiquidationEvent(event: any, credentialId: number | null): FinancialTransaction[] {
  const postedDate = event.PostedDate ? new Date(event.PostedDate) : null;
  if (!postedDate || isNaN(postedDate.getTime())) return [];

  const proceeds = event.LiquidationProceedAmount?.CurrencyAmount || 0;
  const fee = event.LiquidationFeeAmount?.CurrencyAmount || 0;
  const total = proceeds + fee;

  const transactionId = generateTransactionId('', postedDate, 'Liquidations', event.AmazonOrderId || '', event.OriginalRemovalOrderId || '', total);
  const dateOnly = computeDateOnly(postedDate, '');

  return [{
    transaction_id: transactionId, file_name: 'sp-api-sync',
    transaction_date: postedDate, date_only: dateOnly,
    type: 'Liquidations', category_type: 'Liquidations',
    order_id: event.AmazonOrderId || '', sku: '',
    description: `Removal: ${event.OriginalRemovalOrderId || ''}`,
    marketplace: '', marketplace_code: '', fulfillment: 'FBA', order_postal: '',
    quantity: 0,
    product_sales: 0, promotional_rebates: 0, selling_fees: 0,
    fba_fees: fee, other_transaction_fees: 0, other: 0,
    vat: 0, liquidations: proceeds, total,
    credential_id: credentialId,
  }];
}

function flattenCouponEvent(event: any, credentialId: number | null): FinancialTransaction[] {
  const postedDate = event.PostedDate ? new Date(event.PostedDate) : null;
  if (!postedDate || isNaN(postedDate.getTime())) return [];

  const value = event.CouponValueAmount?.CurrencyAmount || 0;
  const fee = event.ClipOrRedemptionFeeAmount?.CurrencyAmount || 0;
  const total = value + fee;

  const transactionId = generateTransactionId('', postedDate, 'Coupon', event.CouponId || '', '', total);
  const dateOnly = computeDateOnly(postedDate, '');

  return [{
    transaction_id: transactionId, file_name: 'sp-api-sync',
    transaction_date: postedDate, date_only: dateOnly,
    type: 'Coupon Payment', category_type: 'Adjustment',
    order_id: '', sku: '', description: event.SellerCouponDescription || 'Coupon',
    marketplace: '', marketplace_code: '', fulfillment: 'Unknown', order_postal: '',
    quantity: event.TotalRedemptionCount || 0,
    product_sales: 0, promotional_rebates: value, selling_fees: 0,
    fba_fees: 0, other_transaction_fees: fee, other: 0,
    vat: 0, liquidations: 0, total,
    credential_id: credentialId,
  }];
}

function flattenProductAdsEvent(event: any, credentialId: number | null): FinancialTransaction {
  const postedDate = event.postedDate ? new Date(event.postedDate) : new Date();
  const total = event.transactionValue?.CurrencyAmount || 0;

  const transactionId = generateTransactionId('', postedDate, 'ProductAds', event.invoiceId || '', event.transactionType || '', total);
  const dateOnly = computeDateOnly(postedDate, '');

  return {
    transaction_id: transactionId, file_name: 'sp-api-sync',
    transaction_date: postedDate, date_only: dateOnly,
    type: `Product Ads - ${event.transactionType || 'Charge'}`, category_type: 'Service Fee',
    order_id: event.invoiceId || '', sku: '',
    description: `Product Advertising ${event.transactionType || ''}`,
    marketplace: '', marketplace_code: '', fulfillment: 'Unknown', order_postal: '',
    quantity: 0,
    product_sales: 0, promotional_rebates: 0, selling_fees: 0,
    fba_fees: 0, other_transaction_fees: total, other: 0,
    vat: 0, liquidations: 0, total,
    credential_id: credentialId,
  };
}

function flattenRetrochargeEvent(event: any, credentialId: number | null): FinancialTransaction {
  const postedDate = event.PostedDate ? new Date(event.PostedDate) : new Date();
  const baseTax = event.BaseTax?.CurrencyAmount || 0;
  const shippingTax = event.ShippingTax?.CurrencyAmount || 0;
  const total = baseTax + shippingTax;
  const marketplaceValue = event.MarketplaceName || '';
  const marketplaceCode = detectMarketplaceCode(marketplaceValue);

  const transactionId = generateTransactionId(marketplaceCode, postedDate, 'Retrocharge', event.AmazonOrderId || '', '', total);
  const dateOnly = computeDateOnly(postedDate, marketplaceCode);

  return {
    transaction_id: transactionId, file_name: 'sp-api-sync',
    transaction_date: postedDate, date_only: dateOnly,
    type: 'Retrocharge', category_type: 'Others',
    order_id: event.AmazonOrderId || '', sku: '', description: 'Retrocharge tax adjustment',
    marketplace: marketplaceValue, marketplace_code: marketplaceCode,
    fulfillment: 'Unknown', order_postal: '',
    quantity: 0,
    product_sales: 0, promotional_rebates: 0, selling_fees: 0,
    fba_fees: 0, other_transaction_fees: 0, other: total,
    vat: 0, liquidations: 0, total,
    credential_id: credentialId,
  };
}

function flattenDebtRecoveryEvent(event: any, credentialId: number | null): FinancialTransaction {
  const recoveryAmount = event.RecoveryAmount?.CurrencyAmount || 0;
  const debtType = event.DebtRecoveryType || 'DebtRecovery';

  // Use group begin date if available, otherwise current date
  const items = event.DebtRecoveryItemList || [];
  const postedDate = items.length > 0 && items[0].GroupBeginDate
    ? new Date(items[0].GroupBeginDate)
    : new Date();

  const transactionId = generateTransactionId('', postedDate, debtType, '', '', recoveryAmount);
  const dateOnly = computeDateOnly(postedDate, '');

  return {
    transaction_id: transactionId, file_name: 'sp-api-sync',
    transaction_date: postedDate, date_only: dateOnly,
    type: debtType, category_type: 'Others',
    order_id: '', sku: '', description: `Debt recovery: ${debtType}`,
    marketplace: '', marketplace_code: '', fulfillment: 'Unknown', order_postal: '',
    quantity: 0,
    product_sales: 0, promotional_rebates: 0, selling_fees: 0,
    fba_fees: 0, other_transaction_fees: 0, other: recoveryAmount,
    vat: 0, liquidations: 0, total: recoveryAmount,
    credential_id: credentialId,
  };
}

function flattenRemovalShipmentEvent(event: any, credentialId: number | null): FinancialTransaction[] {
  const transactions: FinancialTransaction[] = [];
  const postedDate = event.PostedDate ? new Date(event.PostedDate) : null;
  if (!postedDate || isNaN(postedDate.getTime())) return transactions;

  const orderId = event.OrderId || '';
  const txnType = event.TransactionType || 'Removal';

  for (const item of (event.RemovalShipmentItemList || [])) {
    const fee = item.FeeAmount?.CurrencyAmount || 0;
    const revenue = item.Revenue?.CurrencyAmount || 0;
    const total = fee + revenue;

    const transactionId = generateTransactionId('', postedDate, txnType, orderId, item.FulfillmentNetworkSKU || '', total);
    const dateOnly = computeDateOnly(postedDate, '');

    transactions.push({
      transaction_id: transactionId, file_name: 'sp-api-sync',
      transaction_date: postedDate, date_only: dateOnly,
      type: txnType, category_type: 'Delivery Services',
      order_id: orderId, sku: item.FulfillmentNetworkSKU || '',
      description: `Removal shipment: ${txnType}`,
      marketplace: '', marketplace_code: '', fulfillment: 'FBA', order_postal: '',
      quantity: item.Quantity || 0,
      product_sales: 0, promotional_rebates: 0, selling_fees: 0,
      fba_fees: fee, other_transaction_fees: 0, other: revenue,
      vat: 0, liquidations: 0, total,
      credential_id: credentialId,
    });
  }

  return transactions;
}

function flattenRemovalShipmentAdjustmentEvent(event: any, credentialId: number | null): FinancialTransaction[] {
  const transactions: FinancialTransaction[] = [];
  const postedDate = event.PostedDate ? new Date(event.PostedDate) : null;
  if (!postedDate || isNaN(postedDate.getTime())) return transactions;

  const orderId = event.OrderId || '';
  const txnType = event.TransactionType || 'Removal Adjustment';

  for (const item of (event.RemovalShipmentItemAdjustmentList || [])) {
    const revenue = item.RevenueAdjustment?.CurrencyAmount || 0;
    const total = revenue;

    const transactionId = generateTransactionId('', postedDate, `${txnType}-Adj`, orderId, item.FulfillmentNetworkSKU || '', total);
    const dateOnly = computeDateOnly(postedDate, '');

    transactions.push({
      transaction_id: transactionId, file_name: 'sp-api-sync',
      transaction_date: postedDate, date_only: dateOnly,
      type: `${txnType} Adjustment`, category_type: 'Delivery Services',
      order_id: orderId, sku: item.FulfillmentNetworkSKU || '',
      description: `Removal shipment adjustment: ${txnType}`,
      marketplace: '', marketplace_code: '', fulfillment: 'FBA', order_postal: '',
      quantity: item.AdjustedQuantity || 0,
      product_sales: 0, promotional_rebates: 0, selling_fees: 0,
      fba_fees: 0, other_transaction_fees: 0, other: revenue,
      vat: 0, liquidations: 0, total,
      credential_id: credentialId,
    });
  }

  return transactions;
}
